# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  171701api:
    image: 171701api
    build:
      context: .
      dockerfile: 171701_api/Dockerfile
    ports:
      - 8081:80
        
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:management
    hostname: rabbitmq.local
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      common_network:
        aliases:
          - rabbitmq.local
      
  sample-prod:
    container_name: sample-prod
    image: sample:prod
    ports:
      - '1337:80'
    depends_on:
      - 171701api
      - rabbitmq

  generator_new_name:
    build:
      context: .
      dockerfile: generator/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      common_network:
        
networks:
  common_network:
