# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: api/Dockerfile
    networks:
      - common_network
    depends_on:
      - rabbitmq
        
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:management
    hostname: rabbitmq.local
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      common_network:
        aliases:
          - rabbitmq.local
      
  front:
    image: front
    build:
      context: .
      dockerfile: front/Dockerfile
    networks:
      - common_network
    depends_on:
      - api
    ports:
      - '1338:80'

  generator_new_name:
    build:
      context: .
      dockerfile: generator/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - common_network
        
networks:
  common_network:
