# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  171701api:
    image: 171701api
    build:
      context: .
      dockerfile: 171701_api/Dockerfile
    ports:
      - 8081:80
  sample-prod:
    container_name: sample-prod
    image: sample:prod
    ports:
      - '1337:80'
    depends_on:
      - 171701api
